dist: bionic
language: ruby
rvm:
 — 2.7.2
env:
  matrix:
    - API_ROOT=$deploy_api_uri
  global:
    - RAILS_ENV=test
    - CF_USER=$deploy_username
    - CF_ORG=$deploy_org_name
    - CF_PASS=$deploy_password
services:
  - postgresql
addons:
  postgresql: '11'
sudo: true
install: bundle install --jobs=3 --retry=3
edge: true
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-11-postgis-2.5
  - psql -U postgres -c 'create database cii_test'
  - psql -U postgres -d cii_test -c 'create extension postgis'
script:
  - bundle exec rake db:setup
  - bundle exec rake
  - bundle exec rubocop
before_deploy:
  - echo "install cloudfoundry cli"
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get -qq update
  - sudo apt-get install cf-cli
deploy:
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s development
    on:
      branch: develop
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s testing
    on:
      branch: staging
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s integration
    on:
      branch: integration
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s preproduction
    on:
      branch: main
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s production
    on:
      branch: main
