dist: bionic
language: ruby
rvm:
 — 2.7.2
env:
  matrix:
    - API_ROOT=$deploy_api_uri
  global:
    - RAILS_ENV=test
    - CF_USER=$deploy_username
    - CF_ORG=$deploy_org_name
    - CF_PASS=$deploy_password
services:
  - postgresql
addons:
  postgresql: '11'
sudo: true
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-11-postgis-2.5
  - psql -U postgres -c 'create database cii_test'
  - psql -U postgres -d cii_test -c 'create extension postgis'
install: # script:
  - bundle exec rake db:setup
  - bundle exec rake
  - bundle exec rubocop
deploy:
  edge: true
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s dev
    on:
      repo: Crown-Commercial-Service/conclave-cii-api
      branch: develop
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s testing
    on:
      repo: Crown-Commercial-Service/conclave-cii-api
      branch: staging