dist: bionic
language: ruby
rvm:
 — 2.7.2
deploy:
  edge: true
  provider: cloudfoundry
  api: $deploy_api_uri
  username: $deploy_username
  password: $deploy_password
  organization: $deploy_org_name
  space: $deploy_integration_space_type
  on:
    repo: Crown-Commercial-Service/conclave-cii-api
    branch: integration
env:
  global:
    - RAILS_ENV=test
services:
  - postgresql
addons:
  postgresql: '11'
sudo: true
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-11-postgis-2.5
  - psql -U postgres -c 'create database cii_test'
  - psql -U postgres -d cii_test -c 'create extension postgis'
script:
  - bundle exec rake db:setup
  - bundle exec rake
  - bundle exec rubocop
