module Common
  class StatusCodes
    UNAUTHORIZED = 401
    NOT_FOUND = 404
    DUPLICATE_RESOURCE = 409
    BAD_REQUEST = 400
    SERVICE_UNAVAILABLE = 503
    TOO_MANY_REQUESTS = 429
    FORBIDDEN = 403
  end
end
