name: CII API

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:14-3.2
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cii_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/cii_test
      SPOTLIGHT_CLIENT_ID: "jdoifiowehfwibewiufwer3hiu349y4o83gh8o4g8ob34o4gg393246812634881"
      SPOTLIGHT_CLIENT_SECRET: "bsiuf98328hro3h8or3go8rg8p238o23hiu3r8o23ho8323274981234917298478"
      COMPANIES_HOUSE_API_TOKEN: "KzHV720QsCl6FnJiezFB4LqLoosbfiu326493624162"
      COMPANIES_HOUSE_API_ENDPOINT: "https://api.dummy-information.service.gov.uk"
      DNB_API_ENDPOINT: "https://dummy.dnb.com"
      DNB_USERNAME: "nwfiebfibweibfuewbf8248912"
      DNB_PASSWORD: "wdoieoiefeowif4912679481"
      FINDTHATCHARITY_API_ENDPOINT: "https://find-dummy-thatcharity.uk"
      CLIENT_TOKEN: "1B4B9BBC9ADA4EA65E98A9A32F8D4 F3CAE7C17E2769H3294H293H42984H"
      SECURITY_SERVICE_URL: "http://www.test.com"
      ACCESS_CCS_ADMIN: "test_admin"
      ACCESS_ORGANISATION_ADMIN: "test_org_admin"
      ACCESS_MANAGE_SUBSCRIPTIONS: "test_manage_subscriptions"
      INTEGRATION_TOKEN: "6348G438RT834GR4827GRO8NROWNEORNWEONTR"
      DELETE_TOKEN: "6348G438RT834GR4827GRO834B39UHB32IB5IU23"
      SALESFORCE_AUTH_URL: "https://biwbdqwbdiwebiu.com"
      SALESFORCE_USERNAME: "test@testcommercial.gov.uk"
      SALESFORCE_PASSWORD: "6238g3b282n12o4n"
      SALESFORCE_SECURITY_TOKEN: "nsdn34982328or34go83323j4nji"
      SALESFORCE_CLIENT_ID: "jdoifiowehfwibewiufwer3hiu349y4o83gh8o4g8ob34o4gg39o23g48o22e1223re"
      SALESFORCE_CLIENT_SECRET: "bsiuf98328hro3h8or3go8rg8p238o23hiu3r8o23ho832griui2412e4123"
      CLIENT_ID: "wndiowdio2u2e12e"
      CONFIG_SPOTLIGHT_AUTH_URL: "https://biwbdqwbdiwebiu.com"
      CONFIG_SPOTLIGHT_USERNAME: "test@testcommercial.gov.uk"
      CONFIG_SPOTLIGHT_PASSWORD: "6238g3b28323gg3g"
      CONFIG_SPOTLIGHT_SECURITY_TOKEN: "nsdn34982328or34go83goy23g723v"   
      CONFIG_SPOTLIGHT_CLIENT_ID: "jdoifiowehfwibewiufwer3hiu349y4o83gh8o4g8ob34o4gg39o23g48o23o8go88g34o8"
      CONFIG_SPOTLIGHT_CLIENT_SECRET: "bsiuf98328hro3h8or3go8rg8p238o23hiu3r8o23ho832griuiuhdoweh98ho2hh32"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      
      
      # - name: Load .env.test if present
      #   run: |
      #     if [ -f .env.test ]; then
      #       set -a
      #       source .env.test
      #       set +a

      #       while IFS='=' read -r key _; do
      #         if [[ "$key" =~ ^[[:space:]]*# ]] || [[ "$key" =~ ^[[:space:]]*$ ]]; then
      #           continue
      #         fi

      #         key="$(echo "$key" | tr -d '[:space:]')"
      #         printf '%s=%s\n' "$key" "${!key}" >> "$GITHUB_ENV"
      #       done < .env.test
      #     fi

      - name: Setup DB
        run: bundle exec rails db:create db:schema:load --trace

      - name: Run migrations
        run: bundle exec rails db:migrate RAILS_ENV=test

      - name: Seed test data
        run: bundle exec rails db:seed RAILS_ENV=test

      - name: Run tests
        run: bundle exec rspec

      - name: Run rubocop
        run: bundle exec rubocop