name: CII API

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:14-3.2
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cii_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/cii_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      
      
      - name: Load .env.test if present
        run: |
          if [ -f .env.test ]; then
            set -a
            source .env.test
            set +a

            while IFS='=' read -r key _; do
              if [[ "$key" =~ ^[[:space:]]*# ]] || [[ "$key" =~ ^[[:space:]]*$ ]]; then
                continue
              fi

              key="$(echo "$key" | tr -d '[:space:]')"
              printf '%s=%s\n' "$key" "${!key}" >> "$GITHUB_ENV"
            done < .env.test
          fi

      - name: Setup DB
        run: bundle exec rails db:create db:schema:load --trace

      - name: Run migrations
        run: bundle exec rails db:migrate RAILS_ENV=test

      - name: Run tests
        run: bundle exec rspec

      - name: Run rubocop
        run: bundle exec rubocop